services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - plex-search-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      - plex-search-net
    env_file: .env
    volumes:
      - chroma-data:/data/chroma

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    networks:
      - plex-search-net
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5:7b}
      - OLLAMA_EMBED_MODEL=${OLLAMA_EMBED_MODEL:-nomic-embed-text}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  plex-search-net:

volumes:
  ollama-data:
  chroma-data:
