services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    networks:
      - plex-search-net

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-8001}:8000"
    networks:
      - plex-search-net
    env_file: .env
    volumes:
      - chroma-data:/data/chroma

networks:
  plex-search-net:

volumes:
  chroma-data:
